# Generated by Django 5.2.11 on 2026-04-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_dealerstockhistory_dealer_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerStockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active_stock', models.BooleanField(default=True)),
                ('is_selected_by_dealer', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('dealer_selection', 'Dealer Selection'), ('company_added', 'Company Added'), ('system_added', 'System Added')], default='dealer_selection', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_dealer_stocks', to='api.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dealer_stocks', to='api.employee')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_stocks', to='api.dealer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dealer_stocks', to='api.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('dealer', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='DealerStockAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('selected', 'Selected'), ('unselected', 'Unselected')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('action_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action_by_role', models.CharField(blank=True, max_length=100, null=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
                ('dealer_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='api.dealerstockmaster')),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
        migrations.CreateModel(
            name='DealerStockSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sync_logs', to='api.dealer')),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
        ),
    ]
