# Generated by Django 5.2.11 on 2026-04-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_machineinstallation_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('itemname', models.CharField(db_column='itemname', max_length=255)),
                ('itemcode', models.CharField(db_column='itemcode', max_length=100, primary_key=True, serialize=False)),
                ('productcode', models.CharField(db_column='ProductCode', max_length=100)),
                ('itemgroupmasterid', models.IntegerField(blank=True, db_column='ItemGroupMasterId', null=True)),
            ],
            options={
                'db_table': 'itemmaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=100)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('order_quantity', models.PositiveIntegerField()),
                ('pending_quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_completed', 'Partially Completed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to='api.employee')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='api.dealer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_quantity', models.PositiveIntegerField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('pending_after', models.PositiveIntegerField()),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_confirmations', to='api.employee')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='api.purchaseorder')),
            ],
            options={
                'ordering': ['confirmed_at'],
            },
        ),
    ]
