# Generated by Django 5.2.11 on 2026-04-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_ticket_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_gst_no', models.CharField(blank=True, max_length=30, null=True)),
                ('dealer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_selected_by_dealer', models.BooleanField(default=False)),
                ('added_by_role', models.CharField(blank=True, max_length=100, null=True)),
                ('added_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by_role', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('DEALER_SELECTION', 'Dealer Selection'), ('COMPANY_MANUAL', 'Company Manual'), ('SYSTEM_MANUAL', 'System Manual')], default='DEALER_SELECTION', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_dealer_stocks', to='api.employee')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_stocks', to='api.company')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_stocks', to='api.dealer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dealer_stocks', to='api.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('dealer', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='DealerStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADDED', 'Added'), ('UPDATED', 'Updated'), ('REMOVED', 'Removed'), ('CHECKED', 'Checked'), ('UNCHECKED', 'Unchecked')], max_length=20)),
                ('performed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('performed_by_role', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='api.dealerstock')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
        ),
    ]
