# Generated by Django 5.2.11 on 2026-04-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_dealerstock_dealerstockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerstockhistory',
            name='dealer_stock',
        ),
        migrations.RemoveField(
            model_name='dealerstockhistory',
            name='performed_by',
        ),
        migrations.DeleteModel(
            name='DealerStock',
        ),
        migrations.DeleteModel(
            name='DealerStockHistory',
        ),
    ]
