# Generated by Django 5.2.11 on 2026-04-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_dealerstockmaster_dealerstockaudit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerstockmaster',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerstockmaster',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('returned', 'Returned')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealerstockaudit',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('selected', 'Selected'), ('unselected', 'Unselected'), ('sold', 'Sold'), ('returned', 'Returned')], max_length=20),
        ),
        migrations.CreateModel(
            name='DealerStockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('returned_by_name', models.CharField(max_length=255)),
                ('returned_by_role', models.CharField(max_length=100)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
                ('dealer_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='api.dealerstockmaster')),
                ('returned_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
        ),
    ]
