# Generated by Django 5.2.11 on 2026-04-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_dealerstockmaster_sold_date_dealerstockmaster_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineinstallation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_installations', to='api.employee'),
        ),
    ]
